# Generated by Django 6.0.7 on 2026-07-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('New Lead', 'New Lead'), ('Application', 'Application'), ('Converted', 'Converted')], default='New Lead', max_length=50),
        ),
    ]
